### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by SaskiaFreytag** [prafols/rMSIproc#11]
Hi,

I have had problems installing your package since some of the depenencies (see below) have been removed from CRAN. Any recommendations on how to circumvent this problem?

<img width="819" alt="Screen Shot 2022-08-16 at 3 45 29 pm" src="https://user-images.githubusercontent.com/9170680/184806583-39eea2d8-1ece-4a64-b0f3-c285b819bd42.png">

Cheers,

Saskia

**Comment by prafols** [comment]
Hi,
the packages related to RGtk2 were unmaintained and not available anymore on CRAN. We are working to provide a renewed GUI without using them, but it is going to take longer than expected. Nevertheless, we provide a workaround, documented here:

https://github.com/prafols/rMSI2/blob/main/guides/installation.md

Please let me know if this works for you. Best,

Pere
