### ISSUE TITLE
Error: 'open.ff' is not an exported object from 'namespace:ff'

### ISSUE THREAD

**Issue by luketrichardson** [prafols/rMSIproc#9]
After a successful binary file read in, average spectrum calculation, and internal reference spectrum calculation, I received an error (Error: 'close.ff' is not an exported object from 'namespace:ff') after the program began Label-Free Alignment. When I attempted to reopen the same image, I received the error in the subject line (Error: 'open.ff' is not an exported object from 'namespace:ff') after the program began loading the image. Is there a known fix for this?

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.2                         
year           2020                        
month          06                          
day            22                          
svn rev        78730                       
language       R                           
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again

**Comment by luketrichardson** [comment]
Tentatively resolved. At this time, a previous version the ff package works.

From "https://community.rstudio.com/t/unable-to-install-bioconductor-package/75223/2":
Previous version that works is 2.2.14. Directly use this URL to re-install this package and restart Rstudio:
install.packages('https://cran.r-project.org/src/contrib/Archive/ff/ff_2.2-14.tar.gz ',repos=NULL)

type='source' was also required for a successful install for me.

**Comment by prafols** [comment]
I fixed rMSIproc to work properly with the new ff packages.
